version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
      #commands:
      #  - echo $READTHEDOCS_OUTPUT
      #  - mkdir --parents _readthedocs/html/

python:
  install:
    - method: pip
      path: docs/_source
      requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/_source/conf.py
