version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9" # "3.11" # 
  jobs:
    pre_build:
      - ls
      # - conda list
      # - echo $READTHEDOCS_OUTPUT
    post_build:
      - ls
      #- ls _readthedocs/html
      #- ls _readthedocs/html/_sources
      #- rm -rf _readthedocs/html
      #- sphinx-build -b html docs/_source _readthedocs/html

conda:
  environment: docs/environment.yaml

        # python:
        #   install:
        #     - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/_source/conf.py
