version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - pip list
      - echo $READTHEDOCS_OUTPUT
    post_build:
      - ls _readthedocs/html
      - ls _readthedocs/html/_sources
      # - rm -rf _readthedocs/html
      # - sphinx-build -b html docs/_source _readthedocs

conda:
  - environment: environment.yml

        # python:
        #   install:
        #     - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/_source/conf.py
