version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  commands:
    - echo $READTHEDOCS_OUTPUT

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/_source/conf.py
