version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    requirements:
      - "sphinx_atodoc_typehints"
      - "pydata-sphinx-theme"

sphinx:
  configuration: docs/_source/conf.py
