version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
      #commands:
      #  - echo $READTHEDOCS_OUTPUT
      #  - mkdir --parents _readthedocs/html/
  jobs:
    pre_build:
      - pip list


python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: docs/_source/conf.py
